/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package views;

import controllers.addUserController;
import controllers.menuController;
import controllers.professorController;
import controllers.studentController;
import javax.accessibility.AccessibleContext;
import javax.swing.JRootPane;


/**
 *
 * @author facun
 */
public class menuView extends javax.swing.JFrame {

    /**
     * Creates new form menuView
     */
    public menuView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        menuLabel1 = new javax.swing.JLabel();
        menuLabel2 = new javax.swing.JLabel();
        exitButton = new javax.swing.JButton();
        menuStudentButton = new javax.swing.JButton();
        menuProfessorButton = new javax.swing.JButton();
        menuCourseButton = new javax.swing.JButton();
        menuDegreeButton = new javax.swing.JButton();
        menuChangePasswordButton = new javax.swing.JButton();
        menuAddUserButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        menuLabel1.setFont(new java.awt.Font("Arial Black", 0, 36)); // NOI18N
        menuLabel1.setText("MENU");

        menuLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        menuLabel2.setText("jLabel2");

        exitButton.setText("Logout");
        exitButton.setName("exitButton"); // NOI18N
        exitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitButtonActionPerformed(evt);
            }
        });

        menuStudentButton.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        menuStudentButton.setText("Student");
        menuStudentButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuStudentButtonActionPerformed(evt);
            }
        });

        menuProfessorButton.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        menuProfessorButton.setText("Professor");
        menuProfessorButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuProfessorButtonActionPerformed(evt);
            }
        });

        menuCourseButton.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        menuCourseButton.setText("Course");

        menuDegreeButton.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        menuDegreeButton.setText("Degree");

        menuChangePasswordButton.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        menuChangePasswordButton.setText("Change password");

        menuAddUserButton.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        menuAddUserButton.setText("Add user");
        menuAddUserButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuAddUserButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(158, 158, 158)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(exitButton)
                        .addGap(26, 26, 26))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(menuDegreeButton, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(169, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(menuStudentButton, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(menuAddUserButton, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(menuChangePasswordButton, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 203, Short.MAX_VALUE)
                            .addComponent(menuCourseButton, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 203, Short.MAX_VALUE)
                            .addComponent(menuProfessorButton, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 203, Short.MAX_VALUE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 46, Short.MAX_VALUE)
                        .addComponent(menuLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(menuLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(menuLabel1)
                    .addComponent(menuLabel2))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(exitButton)
                        .addGap(20, 20, 20))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(menuStudentButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(menuProfessorButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(menuCourseButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(menuDegreeButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(menuChangePasswordButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(menuAddUserButton)
                        .addContainerGap(52, Short.MAX_VALUE))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void exitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitButtonActionPerformed
        // TODO add your handling code here:
        menuController.exitButton();
    }//GEN-LAST:event_exitButtonActionPerformed

    private void menuStudentButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuStudentButtonActionPerformed
        // TODO add your handling code here:
        studentController.showStudentView();
    }//GEN-LAST:event_menuStudentButtonActionPerformed

    private void menuAddUserButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuAddUserButtonActionPerformed
        // TODO add your handling code here:
        addUserController.showAddUserView();
        addUserController.cleanTextFieldComboBoxAddUser();
    }//GEN-LAST:event_menuAddUserButtonActionPerformed

    private void menuProfessorButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuProfessorButtonActionPerformed
        // TODO add your handling code here:
        professorController.showProfessorView();
    }//GEN-LAST:event_menuProfessorButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(menuView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(menuView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(menuView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(menuView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new menuView().setVisible(true);
            }
        });
    }
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton exitButton;
    private javax.swing.JButton menuAddUserButton;
    private javax.swing.JButton menuChangePasswordButton;
    private javax.swing.JButton menuCourseButton;
    private javax.swing.JButton menuDegreeButton;
    private javax.swing.JLabel menuLabel1;
    private javax.swing.JLabel menuLabel2;
    private javax.swing.JButton menuProfessorButton;
    private javax.swing.JButton menuStudentButton;
    // End of variables declaration//GEN-END:variables

    public javax.swing.JButton getExitButton() {
        return exitButton;
    }

    public void setExitButton(javax.swing.JButton exitButton) {
        this.exitButton = exitButton;
    }

    public javax.swing.JButton getMenuChangePasswordButton() {
        return menuChangePasswordButton;
    }

    public void setMenuChangePasswordButton(javax.swing.JButton menuChangePasswordButton) {
        this.menuChangePasswordButton = menuChangePasswordButton;
    }

    public javax.swing.JButton getMenuCourseButton() {
        return menuCourseButton;
    }

    public void setMenuCourseButton(javax.swing.JButton menuCourseButton) {
        this.menuCourseButton = menuCourseButton;
    }

    public javax.swing.JButton getMenuDegreeButton() {
        return menuDegreeButton;
    }

    public void setMenuDegreeButton(javax.swing.JButton menuDegreeButton) {
        this.menuDegreeButton = menuDegreeButton;
    }

    public javax.swing.JLabel getMenuLabel1() {
        return menuLabel1;
    }

    public void setMenuLabel1(javax.swing.JLabel menuLabel1) {
        this.menuLabel1 = menuLabel1;
    }

    public javax.swing.JLabel getMenuLabel2() {
        return menuLabel2;
    }

    public void setMenuLabel2(javax.swing.JLabel menuLabel2) {
        this.menuLabel2 = menuLabel2;
    }

    public javax.swing.JButton getMenuProfessorButton() {
        return menuProfessorButton;
    }

    public javax.swing.JButton getMenuStudentButton() {
        return menuStudentButton;
    }

    public void setMenuStudentButton(javax.swing.JButton menuStudentButton) {
        this.menuStudentButton = menuStudentButton;
    }

    public javax.swing.JButton getMenuAddUserButton() {
        return menuAddUserButton;
    }

    public void setMenuAddUserButton(javax.swing.JButton menuAddUserButton) {
        this.menuAddUserButton = menuAddUserButton;
    }
}
