/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package views;

import controllers.studentController;

/**
 *
 * @author facun
 */
public class deleteStudentView extends javax.swing.JFrame {

    /**
     * Creates new form deleteStudentView
     */
    public deleteStudentView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        deleteStudentLabel1 = new javax.swing.JLabel();
        deleteStudentTextField1 = new javax.swing.JTextField();
        deleteStudentButton1 = new javax.swing.JButton();
        deleteStudentButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        deleteStudentLabel1.setText("Student ID:");

        deleteStudentButton1.setText("Delete");
        deleteStudentButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteStudentButton1ActionPerformed(evt);
            }
        });

        deleteStudentButton2.setText("Cancel");
        deleteStudentButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteStudentButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(deleteStudentLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(deleteStudentButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(58, 58, 58)
                        .addComponent(deleteStudentButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(89, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(deleteStudentTextField1)
                        .addGap(21, 21, 21))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(deleteStudentLabel1)
                    .addComponent(deleteStudentTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 50, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(deleteStudentButton1)
                    .addComponent(deleteStudentButton2))
                .addGap(14, 14, 14))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void deleteStudentButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteStudentButton1ActionPerformed
        // TODO add your handling code here:
        studentController.deleteButton();
    }//GEN-LAST:event_deleteStudentButton1ActionPerformed

    private void deleteStudentButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteStudentButton2ActionPerformed
        // TODO add your handling code here:
       studentController.hideDeleteStudentView();
    }//GEN-LAST:event_deleteStudentButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(deleteStudentView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(deleteStudentView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(deleteStudentView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(deleteStudentView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new deleteStudentView().setVisible(true);
            }
        });
    }
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton deleteStudentButton1;
    private javax.swing.JButton deleteStudentButton2;
    private javax.swing.JLabel deleteStudentLabel1;
    private javax.swing.JTextField deleteStudentTextField1;
    // End of variables declaration//GEN-END:variables

    public javax.swing.JButton getDeleteStudentButton1() {
        return deleteStudentButton1;
    }

    public void setDeleteStudentButton1(javax.swing.JButton deleteStudentButton1) {
        this.deleteStudentButton1 = deleteStudentButton1;
    }

    public javax.swing.JButton getDeleteStudentButton2() {
        return deleteStudentButton2;
    }

    public void setDeleteStudentButton2(javax.swing.JButton deleteStudentButton2) {
        this.deleteStudentButton2 = deleteStudentButton2;
    }

    public javax.swing.JLabel getDeleteStudentLabel1() {
        return deleteStudentLabel1;
    }

    public void setDeleteStudentLabel1(javax.swing.JLabel deleteStudentLabel1) {
        this.deleteStudentLabel1 = deleteStudentLabel1;
    }

    public javax.swing.JTextField getDeleteStudentTextField1() {
        return deleteStudentTextField1;
    }

    public void setDeleteStudentTextField1(javax.swing.JTextField deleteStudentTextField1) {
        this.deleteStudentTextField1 = deleteStudentTextField1;
    }
}
