/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package views;

import controllers.addUserController;

/**
 *
 * @author facun
 */
public class addUserView extends javax.swing.JFrame {

    /**
     * Creates new form addUserView
     */
    public addUserView() {
        initComponents();
        addUserComboBox2.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        addUserLabel1 = new javax.swing.JLabel();
        addUserComboBox1 = new javax.swing.JComboBox<>();
        addUserLabel2 = new javax.swing.JLabel();
        addUserLabel3 = new javax.swing.JLabel();
        addUserTextField1 = new javax.swing.JTextField();
        addUserLabel4 = new javax.swing.JLabel();
        addUserTextField2 = new javax.swing.JTextField();
        addUserLabel5 = new javax.swing.JLabel();
        addUserTextField3 = new javax.swing.JTextField();
        addUserLabel6 = new javax.swing.JLabel();
        addUserTextField4 = new javax.swing.JTextField();
        addUserTextField5 = new javax.swing.JTextField();
        addUserLabel7 = new javax.swing.JLabel();
        addUserTextField6 = new javax.swing.JTextField();
        addUserButton1 = new javax.swing.JButton();
        addUserLabel8 = new javax.swing.JLabel();
        addUserComboBox2 = new javax.swing.JComboBox<>();
        addUserViewLabel9 = new javax.swing.JLabel();
        addUserButton2 = new javax.swing.JButton();
        addUserLabel9 = new javax.swing.JLabel();
        addUserLabel10 = new javax.swing.JLabel();
        addUserTextField8 = new javax.swing.JTextField();
        addUserTextField7 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        addUserLabel1.setText("User type:");

        addUserComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "...", "Administrator", "Professor" }));
        addUserComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addUserComboBox1ActionPerformed(evt);
            }
        });

        addUserLabel2.setText("Name:");

        addUserLabel3.setText("Lastname:");

        addUserLabel4.setText("DNI:");

        addUserLabel5.setText("Date of birth:");

        addUserLabel6.setText("Nationality:");

        addUserLabel7.setText("Email:");

        addUserButton1.setText("Add user");
        addUserButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addUserButton1ActionPerformed(evt);
            }
        });

        addUserLabel8.setText("Professor type:");

        addUserComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Permanent", "Substitute" }));

        addUserViewLabel9.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        addUserViewLabel9.setText("ADD USER");

        addUserButton2.setText("Close");
        addUserButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addUserButton2ActionPerformed(evt);
            }
        });

        addUserLabel9.setText("Username:");

        addUserLabel10.setText("Password:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(198, 198, 198)
                .addComponent(addUserViewLabel9)
                .addContainerGap(203, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(addUserLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(addUserLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(addUserLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(addUserLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(addUserLabel5)
                    .addComponent(addUserLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(addUserLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(addUserLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(addUserTextField6, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(addUserTextField5, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(addUserTextField4, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(addUserTextField3, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(addUserTextField2, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(addUserTextField1, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(addUserComboBox1, javax.swing.GroupLayout.Alignment.LEADING, 0, 128, Short.MAX_VALUE)
                    .addComponent(addUserComboBox2, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 175, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(addUserButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(addUserButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(addUserLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(addUserLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(addUserTextField8)
                            .addComponent(addUserTextField7))
                        .addGap(19, 19, 19))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(addUserViewLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 15, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addUserComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(addUserLabel1)
                    .addComponent(addUserLabel9)
                    .addComponent(addUserTextField7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addUserTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(addUserLabel2)
                    .addComponent(addUserLabel10)
                    .addComponent(addUserTextField8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addUserTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(addUserLabel3))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addUserTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(addUserLabel4))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addUserTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(addUserLabel5))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addUserTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(addUserLabel6))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addUserTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(addUserLabel7))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addUserLabel8)
                    .addComponent(addUserComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(addUserButton1))
                .addGap(5, 5, 5)
                .addComponent(addUserButton2)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void addUserComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addUserComboBox1ActionPerformed
        // TODO add your handling code here:
        addUserController.selectComboBox1();
    }//GEN-LAST:event_addUserComboBox1ActionPerformed

    private void addUserButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addUserButton1ActionPerformed
        // TODO add your handling code here:
        addUserController.addUserButton();
        addUserController.cleanTextFieldComboBoxAddUser();
    }//GEN-LAST:event_addUserButton1ActionPerformed

    private void addUserButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addUserButton2ActionPerformed
        // TODO add your handling code here:
        addUserController.hideAddUserView();
        addUserController.cleanTextFieldComboBoxAddUser();
    }//GEN-LAST:event_addUserButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(addUserView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(addUserView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(addUserView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(addUserView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new addUserView().setVisible(true);
            }
        });
    }

    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addUserButton1;
    private javax.swing.JButton addUserButton2;
    private javax.swing.JComboBox<String> addUserComboBox1;
    private javax.swing.JComboBox<String> addUserComboBox2;
    private javax.swing.JLabel addUserLabel1;
    private javax.swing.JLabel addUserLabel10;
    private javax.swing.JLabel addUserLabel2;
    private javax.swing.JLabel addUserLabel3;
    private javax.swing.JLabel addUserLabel4;
    private javax.swing.JLabel addUserLabel5;
    private javax.swing.JLabel addUserLabel6;
    private javax.swing.JLabel addUserLabel7;
    private javax.swing.JLabel addUserLabel8;
    private javax.swing.JLabel addUserLabel9;
    private javax.swing.JTextField addUserTextField1;
    private javax.swing.JTextField addUserTextField2;
    private javax.swing.JTextField addUserTextField3;
    private javax.swing.JTextField addUserTextField4;
    private javax.swing.JTextField addUserTextField5;
    private javax.swing.JTextField addUserTextField6;
    private javax.swing.JTextField addUserTextField7;
    private javax.swing.JTextField addUserTextField8;
    private javax.swing.JLabel addUserViewLabel9;
    // End of variables declaration//GEN-END:variables

    public javax.swing.JComboBox<String> getAddUserComboBox1() {
        return addUserComboBox1;
    }

    public void setAddUserComboBox1(javax.swing.JComboBox<String> addUserComboBox1) {
        this.addUserComboBox1 = addUserComboBox1;
    }

    public javax.swing.JComboBox<String> getAddUserComboBox2() {
        return addUserComboBox2;
    }

    public void setAddUserComboBox2(javax.swing.JComboBox<String> addUserComboBox2) {
        this.addUserComboBox2 = addUserComboBox2;
    }

    public javax.swing.JLabel getAddUserLabel1() {
        return addUserLabel1;
    }

    public void setAddUserLabel1(javax.swing.JLabel addUserLabel1) {
        this.addUserLabel1 = addUserLabel1;
    }

    public javax.swing.JLabel getAddUserLabel2() {
        return addUserLabel2;
    }

    public void setAddUserLabel2(javax.swing.JLabel addUserLabel2) {
        this.addUserLabel2 = addUserLabel2;
    }

    public javax.swing.JLabel getAddUserLabel3() {
        return addUserLabel3;
    }

    public void setAddUserLabel3(javax.swing.JLabel addUserLabel3) {
        this.addUserLabel3 = addUserLabel3;
    }

    public javax.swing.JLabel getAddUserLabel4() {
        return addUserLabel4;
    }

    public void setAddUserLabel4(javax.swing.JLabel addUserLabel4) {
        this.addUserLabel4 = addUserLabel4;
    }

    public javax.swing.JLabel getAddUserLabel5() {
        return addUserLabel5;
    }

    public void setAddUserLabel5(javax.swing.JLabel addUserLabel5) {
        this.addUserLabel5 = addUserLabel5;
    }

    public javax.swing.JLabel getAddUserLabel6() {
        return addUserLabel6;
    }

    public void setAddUserLabel6(javax.swing.JLabel addUserLabel6) {
        this.addUserLabel6 = addUserLabel6;
    }

    public javax.swing.JLabel getAddUserLabel7() {
        return addUserLabel7;
    }

    public void setAddUserLabel7(javax.swing.JLabel addUserLabel7) {
        this.addUserLabel7 = addUserLabel7;
    }

    public javax.swing.JLabel getAddUserLabel8() {
        return addUserLabel8;
    }

    public void setAddUserLabel8(javax.swing.JLabel addUserLabel8) {
        this.addUserLabel8 = addUserLabel8;
    }
    
    public javax.swing.JLabel getAddUserViewLabel9() {
        return addUserViewLabel9;
    }

    public void setAddUserViewLabel9(javax.swing.JLabel addUserViewLabel9) {
        this.addUserViewLabel9 = addUserViewLabel9;
    }

    public javax.swing.JTextField getAddUserTextField1() {
        return addUserTextField1;
    }

    public void setAddUserTextField1(javax.swing.JTextField addUserTextField1) {
        this.addUserTextField1 = addUserTextField1;
    }

    public javax.swing.JTextField getAddUserTextField2() {
        return addUserTextField2;
    }

    public void setAddUserTextField2(javax.swing.JTextField addUserTextField2) {
        this.addUserTextField2 = addUserTextField2;
    }

    public javax.swing.JTextField getAddUserTextField3() {
        return addUserTextField3;
    }

    public void setAddUserTextField3(javax.swing.JTextField addUserTextField3) {
        this.addUserTextField3 = addUserTextField3;
    }

    public javax.swing.JTextField getAddUserTextField4() {
        return addUserTextField4;
    }

    public void setAddUserTextField4(javax.swing.JTextField addUserTextField4) {
        this.addUserTextField4 = addUserTextField4;
    }

    public javax.swing.JTextField getAddUserTextField5() {
        return addUserTextField5;
    }

    public void setAddUserTextField5(javax.swing.JTextField addUserTextField5) {
        this.addUserTextField5 = addUserTextField5;
    }

    public javax.swing.JTextField getAddUserTextField6() {
        return addUserTextField6;
    }

    public void setAddUserTextField6(javax.swing.JTextField addUserTextField6) {
        this.addUserTextField6 = addUserTextField6;
    }

    public javax.swing.JButton getAddUserButton1() {
        return addUserButton1;
    }

    public void setAddUserButton1(javax.swing.JButton addUserButton1) {
        this.addUserButton1 = addUserButton1;
    }

    public javax.swing.JButton getAddUserButton2() {
        return addUserButton2;
    }

    public void setAddUserButton2(javax.swing.JButton addUserButton2) {
        this.addUserButton2 = addUserButton2;
    }

    public javax.swing.JLabel getAddUserLabel10() {
        return addUserLabel10;
    }

    public void setAddUserLabel10(javax.swing.JLabel addUserLabel10) {
        this.addUserLabel10 = addUserLabel10;
    }

    public javax.swing.JLabel getAddUserLabel9() {
        return addUserLabel9;
    }

    public void setAddUserLabel9(javax.swing.JLabel addUserLabel9) {
        this.addUserLabel9 = addUserLabel9;
    }

    public javax.swing.JTextField getAddUserTextField7() {
        return addUserTextField7;
    }

    public void setAddUserTextField7(javax.swing.JTextField addUserTextField7) {
        this.addUserTextField7 = addUserTextField7;
    }

    public javax.swing.JTextField getAddUserTextField8() {
        return addUserTextField8;
    }

    public void setAddUserTextField8(javax.swing.JTextField addUserTextField8) {
        this.addUserTextField8 = addUserTextField8;
    }
}
