/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package views;

import controllers.changePasswordController;

/**
 *
 * @author facun
 */
public class changePasswordView extends javax.swing.JFrame {

    /**
     * Creates new form changePasswordView
     */
    public changePasswordView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        changePasswordLabel2 = new javax.swing.JLabel();
        changePasswordButton1 = new javax.swing.JButton();
        changePasswordLabel1 = new javax.swing.JLabel();
        changePasswordTextField1 = new javax.swing.JTextField();
        changePasswordTextField2 = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        changePasswordLabel2.setText("New password:");

        changePasswordButton1.setText("Update");
        changePasswordButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                changePasswordButton1ActionPerformed(evt);
            }
        });

        changePasswordLabel1.setText("User:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(changePasswordButton1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(53, 53, 53)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(changePasswordLabel1)
                            .addComponent(changePasswordLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(changePasswordTextField1)
                            .addComponent(changePasswordTextField2, javax.swing.GroupLayout.DEFAULT_SIZE, 209, Short.MAX_VALUE))
                        .addGap(0, 40, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(26, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(changePasswordLabel1)
                    .addComponent(changePasswordTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(changePasswordLabel2)
                    .addComponent(changePasswordTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addComponent(changePasswordButton1)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void changePasswordButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_changePasswordButton1ActionPerformed
        // TODO add your handling code here:
        changePasswordController.changePass();
    }//GEN-LAST:event_changePasswordButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(changePasswordView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(changePasswordView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(changePasswordView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(changePasswordView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new changePasswordView().setVisible(true);
            }
        });
    }
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton changePasswordButton1;
    private javax.swing.JLabel changePasswordLabel1;
    private javax.swing.JLabel changePasswordLabel2;
    private javax.swing.JTextField changePasswordTextField1;
    private javax.swing.JPasswordField changePasswordTextField2;
    // End of variables declaration//GEN-END:variables

    public javax.swing.JButton getChangePasswordButton1() {
        return changePasswordButton1;
    }

    public void setChangePasswordButton1(javax.swing.JButton changePasswordButton1) {
        this.changePasswordButton1 = changePasswordButton1;
    }

    public javax.swing.JLabel getChangePasswordLabel1() {
        return changePasswordLabel2;
    }

    public void setChangePasswordLabel1(javax.swing.JLabel changePasswordLabel1) {
        this.changePasswordLabel2 = changePasswordLabel1;
    }

    public javax.swing.JLabel getChangePasswordLabel2() {
        return changePasswordLabel2;
    }

    public void setChangePasswordLabel2(javax.swing.JLabel changePasswordLabel2) {
        this.changePasswordLabel2 = changePasswordLabel2;
    }

    public javax.swing.JTextField getChangePasswordTextField1() {
        return changePasswordTextField1;
    }

    public void setChangePasswordTextField1(javax.swing.JTextField changePasswordTextField1) {
        this.changePasswordTextField1 = changePasswordTextField1;
    }

    public javax.swing.JTextField getChangePasswordTextField2() {
        return changePasswordTextField2;
    }
}
