/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package views;

import controllers.studentController;

/**
 *
 * @author facun
 */
public class editStudentView extends javax.swing.JFrame {

    /**
     * Creates new form editStudentView
     */
    public editStudentView() {
        initComponents();
        editStudentLabel2.setEnabled(false);
        editStudentLabel3.setEnabled(false);
        editStudentLabel4.setEnabled(false);
        editStudentLabel5.setEnabled(false);
        editStudentLabel6.setEnabled(false);
        editStudentLabel7.setEnabled(false);
        editStudentTextField2.setEnabled(false);
        editStudentTextField3.setEnabled(false);
        editStudentTextField4.setEnabled(false);
        editStudentTextField5.setEnabled(false);
        editStudentComboBox1.setEnabled(false);
        editStudentComboBox2.setEnabled(false);
        editEditStudentButton.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        editStudentLabel2 = new javax.swing.JLabel();
        editStudentTextField2 = new javax.swing.JTextField();
        searchEditStudentButton = new javax.swing.JButton();
        editStudentLabel3 = new javax.swing.JLabel();
        editStudentLabel4 = new javax.swing.JLabel();
        editStudentLabel6 = new javax.swing.JLabel();
        editStudentLabel7 = new javax.swing.JLabel();
        editStudentLabel5 = new javax.swing.JLabel();
        editStudentLabel1 = new javax.swing.JLabel();
        editStudentTextField4 = new javax.swing.JTextField();
        editStudentTextField1 = new javax.swing.JTextField();
        editStudentTextField3 = new javax.swing.JTextField();
        editStudentTextField5 = new javax.swing.JTextField();
        editStudentComboBox1 = new javax.swing.JComboBox<>();
        editStudentComboBox2 = new javax.swing.JComboBox<>();
        editEditStudentButton = new javax.swing.JButton();
        cancelEditStudentButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        editStudentLabel2.setText("DNI:");

        searchEditStudentButton.setText("Search");
        searchEditStudentButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchEditStudentButtonActionPerformed(evt);
            }
        });

        editStudentLabel3.setText("Name:");

        editStudentLabel4.setText("Lastname:");

        editStudentLabel6.setText("Status:");

        editStudentLabel7.setText("Degree:");

        editStudentLabel5.setText("Nationality:");

        editStudentLabel1.setText("StudentID:");

        editStudentTextField3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editStudentTextField3ActionPerformed(evt);
            }
        });

        editStudentComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "...", "active", "inactive", "graduated" }));

        editStudentComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "...", "Electrical Engineering", "Civil Engineering", "Mechanical Engineering" }));

        editEditStudentButton.setText("Edit");
        editEditStudentButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editEditStudentButtonActionPerformed(evt);
            }
        });

        cancelEditStudentButton.setText("Cancel");
        cancelEditStudentButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelEditStudentButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(editStudentLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(editStudentTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(searchEditStudentButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(editStudentLabel6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(editStudentLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, 67, Short.MAX_VALUE)
                                .addComponent(editStudentLabel7, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(editStudentLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(editStudentLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(editStudentLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(editStudentTextField2)
                            .addComponent(editStudentTextField3)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(20, 20, 20)
                                .addComponent(editEditStudentButton, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 53, Short.MAX_VALUE)
                                .addComponent(cancelEditStudentButton, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(36, 36, 36))
                            .addComponent(editStudentTextField5)
                            .addComponent(editStudentTextField4)
                            .addComponent(editStudentComboBox1, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(editStudentComboBox2, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addGap(82, 82, 82))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(searchEditStudentButton, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(editStudentLabel1)
                            .addComponent(editStudentTextField1))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(editStudentLabel2)
                            .addComponent(editStudentTextField2))
                        .addGap(6, 6, 6)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(editStudentLabel3)
                            .addComponent(editStudentTextField3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(editStudentTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(editStudentLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(editStudentTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(editStudentLabel5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(editStudentLabel6))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(editStudentComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(editStudentComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(editStudentLabel7))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(editEditStudentButton)
                    .addComponent(cancelEditStudentButton))
                .addContainerGap(17, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void editStudentTextField3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editStudentTextField3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_editStudentTextField3ActionPerformed

    private void searchEditStudentButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchEditStudentButtonActionPerformed
        // TODO add your handling code here:
        editStudentLabel2.setEnabled(true);
        editStudentLabel3.setEnabled(true);
        editStudentLabel4.setEnabled(true);
        editStudentLabel5.setEnabled(true);
        editStudentLabel6.setEnabled(true);
        editStudentLabel7.setEnabled(true);
        editStudentTextField2.setEnabled(true);
        editStudentTextField3.setEnabled(true);
        editStudentTextField4.setEnabled(true);
        editStudentTextField5.setEnabled(true);
        editStudentComboBox1.setEnabled(true);
        editStudentComboBox2.setEnabled(true);
        editEditStudentButton.setEnabled(true);
        studentController.searchEditButton();
    }//GEN-LAST:event_searchEditStudentButtonActionPerformed

    private void cancelEditStudentButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelEditStudentButtonActionPerformed
        // TODO add your handling code here:
        studentController.view_editStudent.setVisible(false);
        studentController.cleanTextFieldEditStudent();
    }//GEN-LAST:event_cancelEditStudentButtonActionPerformed

    private void editEditStudentButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editEditStudentButtonActionPerformed
        // TODO add your handling code here:
       boolean success = studentController.editButton();
       if(success){studentController.cleanTextFieldEditStudent();}
    }//GEN-LAST:event_editEditStudentButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(editStudentView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(editStudentView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(editStudentView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(editStudentView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new editStudentView().setVisible(true);
            }
            
            public static void showSetEnabledFalse(){
            
            }
            
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cancelEditStudentButton;
    private javax.swing.JButton editEditStudentButton;
    private javax.swing.JComboBox<String> editStudentComboBox1;
    private javax.swing.JComboBox<String> editStudentComboBox2;
    private javax.swing.JLabel editStudentLabel1;
    private javax.swing.JLabel editStudentLabel2;
    private javax.swing.JLabel editStudentLabel3;
    private javax.swing.JLabel editStudentLabel4;
    private javax.swing.JLabel editStudentLabel5;
    private javax.swing.JLabel editStudentLabel6;
    private javax.swing.JLabel editStudentLabel7;
    private javax.swing.JTextField editStudentTextField1;
    private javax.swing.JTextField editStudentTextField2;
    private javax.swing.JTextField editStudentTextField3;
    private javax.swing.JTextField editStudentTextField4;
    private javax.swing.JTextField editStudentTextField5;
    private javax.swing.JButton searchEditStudentButton;
    // End of variables declaration//GEN-END:variables

    public javax.swing.JButton getCancelEditStudentButton() {
        return cancelEditStudentButton;
    }

    public void setCancelEditStudentButton(javax.swing.JButton cancelEditStudentButton) {
        this.cancelEditStudentButton = cancelEditStudentButton;
    }

    public javax.swing.JButton getEditEditStudentButton() {
        return editEditStudentButton;
    }

    public void setEditEditStudentButton(javax.swing.JButton editEditStudentButton) {
        this.editEditStudentButton = editEditStudentButton;
    }

    public javax.swing.JComboBox<String> getEditStudentComboBox1() {
        return editStudentComboBox1;
    }

    public void setEditStudentComboBox1(javax.swing.JComboBox<String> editStudentComboBox1) {
        this.editStudentComboBox1 = editStudentComboBox1;
    }

    public javax.swing.JComboBox<String> getEditStudentComboBox2() {
        return editStudentComboBox2;
    }

    public void setEditStudentComboBox2(javax.swing.JComboBox<String> editStudentComboBox2) {
        this.editStudentComboBox2 = editStudentComboBox2;
    }

    public javax.swing.JLabel getEditStudentLabel1() {
        return editStudentLabel1;
    }

    public void setEditStudentLabel1(javax.swing.JLabel editStudentLabel1) {
        this.editStudentLabel1 = editStudentLabel1;
    }

    public javax.swing.JLabel getEditStudentLabel2() {
        return editStudentLabel2;
    }

    public void setEditStudentLabel2(javax.swing.JLabel editStudentLabel2) {
        this.editStudentLabel2 = editStudentLabel2;
    }

    public javax.swing.JLabel getEditStudentLabel3() {
        return editStudentLabel3;
    }

    public void setEditStudentLabel3(javax.swing.JLabel editStudentLabel3) {
        this.editStudentLabel3 = editStudentLabel3;
    }

    public javax.swing.JLabel getEditStudentLabel4() {
        return editStudentLabel4;
    }

    public void setEditStudentLabel4(javax.swing.JLabel editStudentLabel4) {
        this.editStudentLabel4 = editStudentLabel4;
    }

    public javax.swing.JLabel getEditStudentLabel5() {
        return editStudentLabel5;
    }

    public void setEditStudentLabel5(javax.swing.JLabel editStudentLabel5) {
        this.editStudentLabel5 = editStudentLabel5;
    }

    public javax.swing.JLabel getEditStudentLabel6() {
        return editStudentLabel6;
    }

    public void setEditStudentLabel6(javax.swing.JLabel editStudentLabel6) {
        this.editStudentLabel6 = editStudentLabel6;
    }

    public javax.swing.JLabel getEditStudentLabel7() {
        return editStudentLabel7;
    }

    public void setEditStudentLabel7(javax.swing.JLabel editStudentLabel7) {
        this.editStudentLabel7 = editStudentLabel7;
    }

    public javax.swing.JTextField getEditStudentTextField1() {
        return editStudentTextField1;
    }

    public void setEditStudentTextField1(javax.swing.JTextField editStudentTextField1) {
        this.editStudentTextField1 = editStudentTextField1;
    }

    public javax.swing.JTextField getEditStudentTextField2() {
        return editStudentTextField2;
    }

    public void setEditStudentTextField2(javax.swing.JTextField editStudentTextField2) {
        this.editStudentTextField2 = editStudentTextField2;
    }

    public javax.swing.JTextField getEditStudentTextField3() {
        return editStudentTextField3;
    }

    public void setEditStudentTextField3(javax.swing.JTextField editStudentTextField3) {
        this.editStudentTextField3 = editStudentTextField3;
    }

    public javax.swing.JTextField getEditStudentTextField4() {
        return editStudentTextField4;
    }

    public void setEditStudentTextField4(javax.swing.JTextField editStudentTextField4) {
        this.editStudentTextField4 = editStudentTextField4;
    }

    public javax.swing.JTextField getEditStudentTextField5() {
        return editStudentTextField5;
    }

    public void setEditStudentTextField5(javax.swing.JTextField editStudentTextField5) {
        this.editStudentTextField5 = editStudentTextField5;
    }

    public javax.swing.JButton getSearchEditStudentButton() {
        return searchEditStudentButton;
    }

    public void setSearchEditStudentButton(javax.swing.JButton searchEditStudentButton) {
        this.searchEditStudentButton = searchEditStudentButton;
    }
}
