/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package views;

import controllers.professorController;

/**
 *
 * @author facun
 */
public class searchProfessorView extends javax.swing.JFrame {

    /**
     * Creates new form searchProfessorView
     */
    public searchProfessorView() {
        initComponents();
        searchProfessorTextField2.setEnabled(false);
        searchProfessorTextField3.setEnabled(false);
        searchProfessorTextField4.setEnabled(false);
        searchProfessorTextField5.setEnabled(false);
        searchProfessorTextField6.setEnabled(false);
        searchProfessorTextField7.setEnabled(false);
        searchProfessorTextField8.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        searchProfessorLabel1 = new javax.swing.JLabel();
        searchProfessorTextField1 = new javax.swing.JTextField();
        searchProfessorButton1 = new javax.swing.JButton();
        searchProfessorLabel2 = new javax.swing.JLabel();
        searchProfessorTextField2 = new javax.swing.JTextField();
        searchProfessorLabel3 = new javax.swing.JLabel();
        searchProfessorTextField3 = new javax.swing.JTextField();
        searchProfessorLabel4 = new javax.swing.JLabel();
        searchProfessorTextField4 = new javax.swing.JTextField();
        searchProfessorLabel5 = new javax.swing.JLabel();
        searchProfessorTextField5 = new javax.swing.JTextField();
        searchProfessorLabel6 = new javax.swing.JLabel();
        searchProfessorTextField6 = new javax.swing.JTextField();
        searchProfessorLabel7 = new javax.swing.JLabel();
        searchProfessorTextField7 = new javax.swing.JTextField();
        searchProfessorLabel8 = new javax.swing.JLabel();
        searchProfessorTextField8 = new javax.swing.JTextField();
        searchProfessorButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        searchProfessorLabel1.setText("Professor ID:");

        searchProfessorButton1.setText("Search");
        searchProfessorButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchProfessorButton1ActionPerformed(evt);
            }
        });

        searchProfessorLabel2.setText("Name:");

        searchProfessorLabel3.setText("Lastname:");

        searchProfessorLabel4.setText("DNI:");

        searchProfessorTextField4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchProfessorTextField4ActionPerformed(evt);
            }
        });

        searchProfessorLabel5.setText("Email:");

        searchProfessorTextField5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchProfessorTextField5ActionPerformed(evt);
            }
        });

        searchProfessorLabel6.setText("Date of birth:");

        searchProfessorTextField6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchProfessorTextField6ActionPerformed(evt);
            }
        });

        searchProfessorLabel7.setText("Nationality:");

        searchProfessorLabel8.setText("Type:");

        searchProfessorButton2.setText("Close");
        searchProfessorButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchProfessorButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(searchProfessorLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(searchProfessorLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(26, 26, 26)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(searchProfessorLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(searchProfessorLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(searchProfessorLabel1)
                                    .addComponent(searchProfessorLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(searchProfessorLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, 83, Short.MAX_VALUE)
                                    .addComponent(searchProfessorLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(18, 18, 18)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(searchProfessorTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(searchProfessorTextField8)
                            .addComponent(searchProfessorTextField7)
                            .addComponent(searchProfessorTextField6)
                            .addComponent(searchProfessorTextField5)
                            .addComponent(searchProfessorTextField4)
                            .addComponent(searchProfessorTextField2)
                            .addComponent(searchProfessorTextField3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(searchProfessorButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(searchProfessorButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(searchProfessorLabel1)
                    .addComponent(searchProfessorTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(searchProfessorButton1))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(searchProfessorTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(searchProfessorLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(searchProfessorLabel3)
                    .addComponent(searchProfessorTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(searchProfessorLabel4)
                    .addComponent(searchProfessorTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(searchProfessorLabel5)
                    .addComponent(searchProfessorTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(searchProfessorLabel6)
                    .addComponent(searchProfessorTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(searchProfessorTextField7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(searchProfessorLabel7))
                .addGap(7, 7, 7)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(searchProfessorLabel8)
                    .addComponent(searchProfessorTextField8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 24, Short.MAX_VALUE)
                .addComponent(searchProfessorButton2)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void searchProfessorButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchProfessorButton1ActionPerformed
        // TODO add your handling code here:
        professorController.loupeButton();
    }//GEN-LAST:event_searchProfessorButton1ActionPerformed

    private void searchProfessorTextField4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchProfessorTextField4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_searchProfessorTextField4ActionPerformed

    private void searchProfessorTextField5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchProfessorTextField5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_searchProfessorTextField5ActionPerformed

    private void searchProfessorTextField6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchProfessorTextField6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_searchProfessorTextField6ActionPerformed

    private void searchProfessorButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchProfessorButton2ActionPerformed
        // TODO add your handling code here:
        professorController.hideSearchProfessorView();
        professorController.cleanTextFieldSearchProfessor();
    }//GEN-LAST:event_searchProfessorButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(searchProfessorView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(searchProfessorView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(searchProfessorView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(searchProfessorView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new searchProfessorView().setVisible(true);
            }
        });
    }
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton searchProfessorButton1;
    private javax.swing.JButton searchProfessorButton2;
    private javax.swing.JLabel searchProfessorLabel1;
    private javax.swing.JLabel searchProfessorLabel2;
    private javax.swing.JLabel searchProfessorLabel3;
    private javax.swing.JLabel searchProfessorLabel4;
    private javax.swing.JLabel searchProfessorLabel5;
    private javax.swing.JLabel searchProfessorLabel6;
    private javax.swing.JLabel searchProfessorLabel7;
    private javax.swing.JLabel searchProfessorLabel8;
    private javax.swing.JTextField searchProfessorTextField1;
    private javax.swing.JTextField searchProfessorTextField2;
    private javax.swing.JTextField searchProfessorTextField3;
    private javax.swing.JTextField searchProfessorTextField4;
    private javax.swing.JTextField searchProfessorTextField5;
    private javax.swing.JTextField searchProfessorTextField6;
    private javax.swing.JTextField searchProfessorTextField7;
    private javax.swing.JTextField searchProfessorTextField8;
    // End of variables declaration//GEN-END:variables

    public javax.swing.JButton getSearchProfessorButton1() {
        return searchProfessorButton1;
    }

    public void setSearchProfessorButton1(javax.swing.JButton searchProfessorButton1) {
        this.searchProfessorButton1 = searchProfessorButton1;
    }

    public javax.swing.JButton getSearchProfessorButton2() {
        return searchProfessorButton2;
    }

    public void setSearchProfessorButton2(javax.swing.JButton searchProfessorButton2) {
        this.searchProfessorButton2 = searchProfessorButton2;
    }

    public javax.swing.JLabel getSearchProfessorLabel1() {
        return searchProfessorLabel1;
    }

    public void setSearchProfessorLabel1(javax.swing.JLabel searchProfessorLabel1) {
        this.searchProfessorLabel1 = searchProfessorLabel1;
    }

    public javax.swing.JLabel getSearchProfessorLabel2() {
        return searchProfessorLabel2;
    }

    public void setSearchProfessorLabel2(javax.swing.JLabel searchProfessorLabel2) {
        this.searchProfessorLabel2 = searchProfessorLabel2;
    }

    public javax.swing.JLabel getSearchProfessorLabel3() {
        return searchProfessorLabel3;
    }

    public void setSearchProfessorLabel3(javax.swing.JLabel searchProfessorLabel3) {
        this.searchProfessorLabel3 = searchProfessorLabel3;
    }

    public javax.swing.JLabel getSearchProfessorLabel4() {
        return searchProfessorLabel4;
    }

    public void setSearchProfessorLabel4(javax.swing.JLabel searchProfessorLabel4) {
        this.searchProfessorLabel4 = searchProfessorLabel4;
    }

    public javax.swing.JLabel getSearchProfessorLabel5() {
        return searchProfessorLabel5;
    }

    public void setSearchProfessorLabel5(javax.swing.JLabel searchProfessorLabel5) {
        this.searchProfessorLabel5 = searchProfessorLabel5;
    }

    public javax.swing.JLabel getSearchProfessorLabel6() {
        return searchProfessorLabel6;
    }

    public void setSearchProfessorLabel6(javax.swing.JLabel searchProfessorLabel6) {
        this.searchProfessorLabel6 = searchProfessorLabel6;
    }

    public javax.swing.JLabel getSearchProfessorLabel7() {
        return searchProfessorLabel7;
    }

    public void setSearchProfessorLabel7(javax.swing.JLabel searchProfessorLabel7) {
        this.searchProfessorLabel7 = searchProfessorLabel7;
    }

    public javax.swing.JLabel getSearchProfessorLabel8() {
        return searchProfessorLabel8;
    }

    public void setSearchProfessorLabel8(javax.swing.JLabel searchProfessorLabel8) {
        this.searchProfessorLabel8 = searchProfessorLabel8;
    }

    public javax.swing.JTextField getSearchProfessorTextField1() {
        return searchProfessorTextField1;
    }

    public void setSearchProfessorTextField1(javax.swing.JTextField searchProfessorTextField1) {
        this.searchProfessorTextField1 = searchProfessorTextField1;
    }

    public javax.swing.JTextField getSearchProfessorTextField2() {
        return searchProfessorTextField2;
    }

    public void setSearchProfessorTextField2(javax.swing.JTextField searchProfessorTextField2) {
        this.searchProfessorTextField2 = searchProfessorTextField2;
    }

    public javax.swing.JTextField getSearchProfessorTextField3() {
        return searchProfessorTextField3;
    }

    public void setSearchProfessorTextField3(javax.swing.JTextField searchProfessorTextField3) {
        this.searchProfessorTextField3 = searchProfessorTextField3;
    }

    public javax.swing.JTextField getSearchProfessorTextField4() {
        return searchProfessorTextField4;
    }

    public void setSearchProfessorTextField4(javax.swing.JTextField searchProfessorTextField4) {
        this.searchProfessorTextField4 = searchProfessorTextField4;
    }

    public javax.swing.JTextField getSearchProfessorTextField5() {
        return searchProfessorTextField5;
    }

    public void setSearchProfessorTextField5(javax.swing.JTextField searchProfessorTextField5) {
        this.searchProfessorTextField5 = searchProfessorTextField5;
    }

    public javax.swing.JTextField getSearchProfessorTextField6() {
        return searchProfessorTextField6;
    }

    public void setSearchProfessorTextField6(javax.swing.JTextField searchProfessorTextField6) {
        this.searchProfessorTextField6 = searchProfessorTextField6;
    }

    public javax.swing.JTextField getSearchProfessorTextField7() {
        return searchProfessorTextField7;
    }

    public void setSearchProfessorTextField7(javax.swing.JTextField searchProfessorTextField7) {
        this.searchProfessorTextField7 = searchProfessorTextField7;
    }

    public javax.swing.JTextField getSearchProfessorTextField8() {
        return searchProfessorTextField8;
    }

    public void setSearchProfessorTextField8(javax.swing.JTextField searchProfessorTextField8) {
        this.searchProfessorTextField8 = searchProfessorTextField8;
    }
}
