/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package views;

import controllers.studentController;

/**
 *
 * @author facun
 */
public class searchStudentView extends javax.swing.JFrame {

    /**
     * Creates new form searchStudentView
     */
    public searchStudentView() {
    initComponents();      
    searchStudentTextField2.setEnabled(false);
    searchStudentTextField3.setEnabled(false);
    searchStudentTextField4.setEnabled(false);
    searchStudentTextField5.setEnabled(false);
    searchStudentTextField6.setEnabled(false);
    searchStudentTextField7.setEnabled(false);
    searchStudentTextField8.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        searchStudentLabel1 = new javax.swing.JLabel();
        searchStudentTextField1 = new javax.swing.JTextField();
        searchStudentLabel2 = new javax.swing.JLabel();
        searchStudentLabel3 = new javax.swing.JLabel();
        searchStudentLabel4 = new javax.swing.JLabel();
        searchStudentLabel5 = new javax.swing.JLabel();
        searchStudentLabel6 = new javax.swing.JLabel();
        searchStudentLabel7 = new javax.swing.JLabel();
        searchStudentTextField2 = new javax.swing.JTextField();
        searchStudentTextField3 = new javax.swing.JTextField();
        searchStudentTextField4 = new javax.swing.JTextField();
        searchStudentTextField5 = new javax.swing.JTextField();
        searchStudentTextField6 = new javax.swing.JTextField();
        searchStudentTextField7 = new javax.swing.JTextField();
        searchStudentButton1 = new javax.swing.JButton();
        searchStudentButton2 = new javax.swing.JButton();
        searchStudentLabel8 = new javax.swing.JLabel();
        searchStudentTextField8 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        searchStudentLabel1.setText("Student ID:");

        searchStudentLabel2.setText("Name:");

        searchStudentLabel3.setText("Lastname:");

        searchStudentLabel4.setText("DNI:");

        searchStudentLabel5.setText("Email:");

        searchStudentLabel6.setText("Date of birth:");

        searchStudentLabel7.setText("Nationality:");

        searchStudentTextField4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchStudentTextField4ActionPerformed(evt);
            }
        });

        searchStudentTextField5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchStudentTextField5ActionPerformed(evt);
            }
        });

        searchStudentTextField6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchStudentTextField6ActionPerformed(evt);
            }
        });

        searchStudentButton1.setText("Search");
        searchStudentButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchStudentButton1ActionPerformed(evt);
            }
        });

        searchStudentButton2.setText("Close");
        searchStudentButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchStudentButton2ActionPerformed(evt);
            }
        });

        searchStudentLabel8.setText("Degree:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(searchStudentLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(searchStudentLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(searchStudentLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(searchStudentLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(searchStudentLabel1)
                            .addComponent(searchStudentLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(searchStudentLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, 83, Short.MAX_VALUE)
                            .addComponent(searchStudentLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(searchStudentTextField5)
                    .addComponent(searchStudentTextField6)
                    .addComponent(searchStudentTextField4)
                    .addComponent(searchStudentTextField3)
                    .addComponent(searchStudentTextField2)
                    .addComponent(searchStudentTextField7, javax.swing.GroupLayout.DEFAULT_SIZE, 227, Short.MAX_VALUE)
                    .addComponent(searchStudentTextField1)
                    .addComponent(searchStudentTextField8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(searchStudentButton2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(searchStudentButton1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(searchStudentLabel1)
                    .addComponent(searchStudentTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(searchStudentButton1))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(searchStudentTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(searchStudentLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(searchStudentLabel3)
                    .addComponent(searchStudentTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(searchStudentLabel4)
                    .addComponent(searchStudentTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(searchStudentLabel5)
                    .addComponent(searchStudentTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(searchStudentLabel6)
                    .addComponent(searchStudentTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(searchStudentTextField7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(searchStudentLabel7))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(searchStudentButton2))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(7, 7, 7)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(searchStudentLabel8)
                            .addComponent(searchStudentTextField8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(13, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void searchStudentTextField4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchStudentTextField4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_searchStudentTextField4ActionPerformed

    private void searchStudentTextField5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchStudentTextField5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_searchStudentTextField5ActionPerformed

    private void searchStudentTextField6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchStudentTextField6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_searchStudentTextField6ActionPerformed

    private void searchStudentButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchStudentButton1ActionPerformed
        // TODO add your handling code here:
        studentController.loupeButton();
        
    }//GEN-LAST:event_searchStudentButton1ActionPerformed

    private void searchStudentButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchStudentButton2ActionPerformed
        // TODO add your handling code here:
        studentController.hideSearchStudentView();
        studentController.cleanTextFieldSearchStudent();
    }//GEN-LAST:event_searchStudentButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(searchStudentView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(searchStudentView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(searchStudentView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(searchStudentView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new searchStudentView().setVisible(true);
            }
        });
    }

    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton searchStudentButton1;
    private javax.swing.JButton searchStudentButton2;
    private javax.swing.JLabel searchStudentLabel1;
    private javax.swing.JLabel searchStudentLabel2;
    private javax.swing.JLabel searchStudentLabel3;
    private javax.swing.JLabel searchStudentLabel4;
    private javax.swing.JLabel searchStudentLabel5;
    private javax.swing.JLabel searchStudentLabel6;
    private javax.swing.JLabel searchStudentLabel7;
    private javax.swing.JLabel searchStudentLabel8;
    private javax.swing.JTextField searchStudentTextField1;
    private javax.swing.JTextField searchStudentTextField2;
    private javax.swing.JTextField searchStudentTextField3;
    private javax.swing.JTextField searchStudentTextField4;
    private javax.swing.JTextField searchStudentTextField5;
    private javax.swing.JTextField searchStudentTextField6;
    private javax.swing.JTextField searchStudentTextField7;
    private javax.swing.JTextField searchStudentTextField8;
    // End of variables declaration//GEN-END:variables

    public javax.swing.JButton getSearchStudentButton1() {
        return searchStudentButton1;
    }

    public void setSearchStudentButton1(javax.swing.JButton searchStudentButton1) {
        this.searchStudentButton1 = searchStudentButton1;
    }

    public javax.swing.JButton getSearchStudentButton2() {
        return searchStudentButton2;
    }

    public void setSearchStudentButton2(javax.swing.JButton searchStudentButton2) {
        this.searchStudentButton2 = searchStudentButton2;
    }

    public javax.swing.JLabel getSearchStudentLabel1() {
        return searchStudentLabel1;
    }

    public void setSearchStudentLabel1(javax.swing.JLabel searchStudentLabel1) {
        this.searchStudentLabel1 = searchStudentLabel1;
    }

    public javax.swing.JLabel getSearchStudentLabel2() {
        return searchStudentLabel2;
    }

    public void setSearchStudentLabel2(javax.swing.JLabel searchStudentLabel2) {
        this.searchStudentLabel2 = searchStudentLabel2;
    }

    public javax.swing.JLabel getSearchStudentLabel3() {
        return searchStudentLabel3;
    }

    public void setSearchStudentLabel3(javax.swing.JLabel searchStudentLabel3) {
        this.searchStudentLabel3 = searchStudentLabel3;
    }

    public javax.swing.JLabel getSearchStudentLabel4() {
        return searchStudentLabel4;
    }

    public void setSearchStudentLabel4(javax.swing.JLabel searchStudentLabel4) {
        this.searchStudentLabel4 = searchStudentLabel4;
    }

    public javax.swing.JLabel getSearchStudentLabel5() {
        return searchStudentLabel5;
    }

    public void setSearchStudentLabel5(javax.swing.JLabel searchStudentLabel5) {
        this.searchStudentLabel5 = searchStudentLabel5;
    }

    public javax.swing.JLabel getSearchStudentLabel6() {
        return searchStudentLabel6;
    }

    public void setSearchStudentLabel6(javax.swing.JLabel searchStudentLabel6) {
        this.searchStudentLabel6 = searchStudentLabel6;
    }

    public javax.swing.JLabel getSearchStudentLabel7() {
        return searchStudentLabel7;
    }

    public void setSearchStudentLabel7(javax.swing.JLabel searchStudentLabel7) {
        this.searchStudentLabel7 = searchStudentLabel7;
    }

    public javax.swing.JTextField getSearchStudentTextField1() {
        return searchStudentTextField1;
    }

    public void setSearchStudentTextField1(javax.swing.JTextField searchStudentTextField1) {
        this.searchStudentTextField1 = searchStudentTextField1;
    }

    public javax.swing.JTextField getSearchStudentTextField2() {
        return searchStudentTextField2;
    }

    public void setSearchStudentTextField2(javax.swing.JTextField searchStudentTextField2) {
        this.searchStudentTextField2 = searchStudentTextField2;
    }

    public javax.swing.JTextField getSearchStudentTextField3() {
        return searchStudentTextField3;
    }

    public void setSearchStudentTextField3(javax.swing.JTextField searchStudentTextField3) {
        this.searchStudentTextField3 = searchStudentTextField3;
    }

    public javax.swing.JTextField getSearchStudentTextField4() {
        return searchStudentTextField4;
    }

    public void setSearchStudentTextField4(javax.swing.JTextField searchStudentTextField4) {
        this.searchStudentTextField4 = searchStudentTextField4;
    }

    public javax.swing.JTextField getSearchStudentTextField5() {
        return searchStudentTextField5;
    }

    public void setSearchStudentTextField5(javax.swing.JTextField searchStudentTextField5) {
        this.searchStudentTextField5 = searchStudentTextField5;
    }

    public javax.swing.JTextField getSearchStudentTextField6() {
        return searchStudentTextField6;
    }

    public void setSearchStudentTextField6(javax.swing.JTextField searchStudentTextField6) {
        this.searchStudentTextField6 = searchStudentTextField6;
    }

    public javax.swing.JTextField getSearchStudentTextField7() {
        return searchStudentTextField7;
    }

    public void setSearchStudentTextField7(javax.swing.JTextField searchStudentTextField7) {
        this.searchStudentTextField7 = searchStudentTextField7;
    }

    public javax.swing.JLabel getSearchStudentLabel8() {
        return searchStudentLabel8;
    }

    public void setSearchStudentLabel8(javax.swing.JLabel searchStudentLabel8) {
        this.searchStudentLabel8 = searchStudentLabel8;
    }

    public javax.swing.JTextField getSearchStudentTextField8() {
        return searchStudentTextField8;
    }

    public void setSearchStudentTextField8(javax.swing.JTextField searchStudentTextField8) {
        this.searchStudentTextField8 = searchStudentTextField8;
    }
}
